### ISSUE TITLE
How to run the project

### ISSUE THREAD

**Issue by NagendraGowda** [hegde-atri/BankingApplication-fe#6]
Please give the step to run Banking app project....

**Comment by hegde-atri** [comment]
Please read the README, the basic instructions are provided in https://hegdeatri.gitbook.io/banking-application/.

You will need the backend project also running https://github.com/hegde-atri/banking-application-be. Connected to your Azure B2C instance and the appropriate database.

You will also need to setup the Backend project with relevant secrets to access your Azure backend. I advise that you create all relevant Azure services under the same resource group, and have another resource group for logging puproses.

Enter your Azure details in the `auth-config.ts` file - https://github.com/hegde-atri/BankingApplication-fe/blob/main/src/app/auth-config.ts

`git clone https://github.com/hegde-atri/BankingApplication-fe.git`
Once you have cloned the directory:
```
cd BankingApplication-fe
npm install
npm start
```

**Comment by hegde-atri** [comment]
Marking the issue as solved. Unfortunately this project is quite hard to plug-n-play as you need some infrastructure setup as a prerequisite.
